FROM python:2.7

# SSH support on Azure
ENV SSH_PASSWD "root:Docker!"
RUN apt-get update \
	&& apt-get install -y --no-install-recommends openssh-server \
	&& echo "$SSH_PASSWD" | chpasswd
COPY ./compose/django/sshd_config /etc/ssh/

ARG REQUIREMENTS_FILE=production.txt

RUN mkdir /code/
WORKDIR /code/
COPY requirements /code/requirements
RUN pip install -r /code/requirements/$REQUIREMENTS_FILE

ADD . /code/

# Call collectstatic (customize the following line with the minimal environment variables needed for manage.py to run):
RUN python manage.py collectstatic --noinput --settings=config.settings.test

# uWSGI will listen on this port
EXPOSE 2222 80

RUN service ssh start

# Start
ENTRYPOINT ["/code/compose/django/entrypoint.sh"]

CMD ["/code/compose/django/gunicorn.sh"]


#FROM python:3.4
FROM python:2.7

ARG REQUIREMENTS_FILE=production.txt

RUN mkdir /code
WORKDIR /code

COPY requirements /code/requirements
RUN pip install -r /code/requirements/$REQUIREMENTS_FILE

ADD . /code/

# ssh
ENV SSH_PASSWD "root:Docker!"
RUN apt-get update \
        && apt-get install -y --no-install-recommends dialog \
        && apt-get update \
	&& apt-get install -y --no-install-recommends openssh-server \
	&& echo "$SSH_PASSWD" | chpasswd

COPY sshd_config /etc/ssh/
COPY init.sh /usr/local/bin/
#COPY gunicorn.sh /code/

#RUN chmod u+x /usr/local/bin/init.sh
#RUN chmod u+x /code/gunicorn.sh
#EXPOSE 2222 80
#CMD ["python", "/code/manage.py", "runserver", "0.0.0.0:8080"]
ENTRYPOINT ["init.sh"]

#COPY entrypoint.sh /code/entrypoint.sh
#RUN chmod +x /code/entrypoint.sh
#ENTRYPOINT ["/code/entrypoint.sh"]

#CMD ["/code/gunicorn.sh"]

#################
FROM python:2.7

RUN mkdir /code
WORKDIR /code
COPY requirements /code/requirements
RUN pip install -r /code/requirements/production.txt
ADD . /code/

# ssh
ENV SSH_PASSWD "root:Docker!"
RUN apt-get update \
        && apt-get install -y --no-install-recommends dialog \
        && apt-get update \
	&& apt-get install -y --no-install-recommends openssh-server \
	&& echo "$SSH_PASSWD" | chpasswd

COPY sshd_config /etc/ssh/
COPY init.sh /usr/local/bin/

RUN chmod u+x /usr/local/bin/init.sh
EXPOSE 8000 2222
#CMD ["python", "/code/manage.py", "runserver", "0.0.0.0:8000"]
ENTRYPOINT ["init.sh"]

