version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=referral_platform

  django:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REQUIREMENTS_FILE=local.txt
    command: start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=referral_platform
      - DATABASE_URL=postgres://referral_platform:postgres@postgres:5432/referral_platform
      - USE_DOCKER=yes
    volumes:
      - .:/code
      - .:/home/LogFiles
    ports:
      - "8000:8000"


  pycharm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REQUIREMENTS_FILE=local.txt
    command: start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=referral_platform
      - DATABASE_URL=postgres://referral_platform:postgres@postgres:5432/referral_platform
    volumes:
      - .:/code
      - .:/home/LogFiles



