# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-10 17:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170610_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='post_test',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='pre_test',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
