# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-11 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170610_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(default=b'enrolled', max_length=50),
        ),
    ]
