# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-11 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170611_1525'),
        ('courses', '0006_auto_20170611_2239'),
    ]

    operations = [
    ]
