# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-12 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_merge'),
        ('courses', '0007_auto_20170612_0022'),
    ]

    operations = [
    ]
