# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-07 14:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_remove_location_pilot_in_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('assessment_form', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BLN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('english_arabic', 'English/Arabic'), ('french_arabic', 'French/Arabic')], max_length=50, null=True), blank=True, null=True, size=None)),
                ('have_labour', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', '\u0643\u0644\u0627'), ('yes_morning', 'Yes - Morning'), ('yes_afternoon', 'Yes - Afternoon')], max_length=50, null=True), blank=True, null=True, size=None)),
                ('labours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('building', 'Building'), ('manufacturing', 'Manufacturing'), ('retail_store', 'Retail / Store'), ('begging', 'Begging'), ('other_many_other', 'Other (hotel, restaurant, transport, personal services such as cleaning, hair care, cooking and childcare)'), ('other', '\u063a\u064a\u0631 \u0630\u0644\u0643 ')], max_length=50, null=True), blank=True, null=True, size=None)),
                ('labour_hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'enrolled'), ('pre_test', 'pre_test'), ('post_test', 'post_test')], default='enrolled', max_length=50)),
                ('pre_test', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('post_test', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('participation', models.CharField(blank=True, choices=[('less_than_5days', 'Less than 5 absence days'), ('5_10_days', '5 to 10 absence days'), ('10_15_days', '10 to 15 absence days'), ('more_than_15days', 'More than 15 absence days')], max_length=100, null=True)),
                ('barriers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('seasonal_work', 'Seasonal work'), ('transportation', 'Transportation'), ('weather', 'Weather'), ('sickness', 'Sickness'), ('security', 'Security'), ('other', '\u063a\u064a\u0631 \u0630\u0644\u0643 ')], max_length=100, null=True), blank=True, null=True, size=None)),
                ('learning_result', models.CharField(blank=True, choices=[('graduated_next_level', 'Graduated to the next level'), ('graduated_to_formal_kg', 'Graduated to formal education - KG'), ('graduated_to_formal_level1', 'Graduated to formal education - Level 1'), ('referred_to_another_program', 'Referred to another program'), ('dropout', 'Dropout from school')], max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('dropout_status', models.BooleanField(default=False)),
                ('moved', models.BooleanField(default=False)),
                ('outreach_barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('new_registry', models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True)),
                ('student_outreached', models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True)),
                ('have_barcode', models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('referral', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('from_same_ngo', 'Referral from the same NGO'), ('from_other_ngo', 'Referral from an other NGO'), ('form_official_reference', 'Referral from an official reference (Mukhtar, Municipality, School Director, etc.)'), ('from_host_community', 'Referral from the host community'), ('from_displaced_community', 'Referral from the displaced community')], max_length=100, null=True), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CBECE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('english_arabic', 'English/Arabic'), ('french_arabic', 'French/Arabic')], max_length=50, null=True), blank=True, null=True, size=None)),
                ('have_labour', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', '\u0643\u0644\u0627'), ('yes_morning', 'Yes - Morning'), ('yes_afternoon', 'Yes - Afternoon')], max_length=50, null=True), blank=True, null=True, size=None)),
                ('labours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('building', 'Building'), ('manufacturing', 'Manufacturing'), ('retail_store', 'Retail / Store'), ('begging', 'Begging'), ('other_many_other', 'Other (hotel, restaurant, transport, personal services such as cleaning, hair care, cooking and childcare)'), ('other', '\u063a\u064a\u0631 \u0630\u0644\u0643 ')], max_length=50, null=True), blank=True, null=True, size=None)),
                ('labour_hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'enrolled'), ('pre_test', 'pre_test'), ('post_test', 'post_test')], default='enrolled', max_length=50)),
                ('pre_test', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('post_test', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('participation', models.CharField(blank=True, choices=[('less_than_5days', 'Less than 5 absence days'), ('5_10_days', '5 to 10 absence days'), ('10_15_days', '10 to 15 absence days'), ('more_than_15days', 'More than 15 absence days')], max_length=100, null=True)),
                ('barriers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('seasonal_work', 'Seasonal work'), ('transportation', 'Transportation'), ('weather', 'Weather'), ('sickness', 'Sickness'), ('security', 'Security'), ('other', '\u063a\u064a\u0631 \u0630\u0644\u0643 ')], max_length=100, null=True), blank=True, null=True, size=None)),
                ('learning_result', models.CharField(blank=True, choices=[('graduated_next_level', 'Graduated to the next level'), ('graduated_to_formal_kg', 'Graduated to formal education - KG'), ('graduated_to_formal_level1', 'Graduated to formal education - Level 1'), ('referred_to_another_program', 'Referred to another program'), ('dropout', 'Dropout from school')], max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('dropout_status', models.BooleanField(default=False)),
                ('moved', models.BooleanField(default=False)),
                ('outreach_barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('new_registry', models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True)),
                ('student_outreached', models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True)),
                ('have_barcode', models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('referral', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('from_same_ngo', 'Referral from the same NGO'), ('from_other_ngo', 'Referral from an other NGO'), ('form_official_reference', 'Referral from an official reference (Mukhtar, Municipality, School Director, etc.)'), ('from_host_community', 'Referral from the host community'), ('from_displaced_community', 'Referral from the displaced community')], max_length=100, null=True), blank=True, null=True, size=None)),
                ('child_muac', models.CharField(blank=True, choices=[('1', '< 11.5 CM (severe malnutrition)'), ('2', '< 12.5 CM (moderate malnutrition)')], max_length=50, null=True)),
                ('referral_reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('absence', 'Absence')], max_length=100, null=True), blank=True, null=True, size=None)),
                ('pre_test_arabic', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True)),
                ('pre_test_language', models.FloatField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True)),
                ('pre_test_math', models.FloatField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True)),
                ('pre_test_science', models.FloatField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True)),
                ('school_readiness', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_cycle', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('english_arabic', 'English/Arabic'), ('french_arabic', 'French/Arabic')], max_length=50, null=True), blank=True, null=True, size=None)),
                ('have_labour', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', '\u0643\u0644\u0627'), ('yes_morning', 'Yes - Morning'), ('yes_afternoon', 'Yes - Afternoon')], max_length=50, null=True), blank=True, null=True, size=None)),
                ('labours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('building', 'Building'), ('manufacturing', 'Manufacturing'), ('retail_store', 'Retail / Store'), ('begging', 'Begging'), ('other_many_other', 'Other (hotel, restaurant, transport, personal services such as cleaning, hair care, cooking and childcare)'), ('other', '\u063a\u064a\u0631 \u0630\u0644\u0643 ')], max_length=50, null=True), blank=True, null=True, size=None)),
                ('labour_hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'enrolled'), ('pre_test', 'pre_test'), ('post_test', 'post_test')], default='enrolled', max_length=50)),
                ('pre_test', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('post_test', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('participation', models.CharField(blank=True, choices=[('less_than_5days', 'Less than 5 absence days'), ('5_10_days', '5 to 10 absence days'), ('10_15_days', '10 to 15 absence days'), ('more_than_15days', 'More than 15 absence days')], max_length=100, null=True)),
                ('barriers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('seasonal_work', 'Seasonal work'), ('transportation', 'Transportation'), ('weather', 'Weather'), ('sickness', 'Sickness'), ('security', 'Security'), ('other', '\u063a\u064a\u0631 \u0630\u0644\u0643 ')], max_length=100, null=True), blank=True, null=True, size=None)),
                ('learning_result', models.CharField(blank=True, choices=[('graduated_next_level', 'Graduated to the next level'), ('graduated_to_formal_kg', 'Graduated to formal education - KG'), ('graduated_to_formal_level1', 'Graduated to formal education - Level 1'), ('referred_to_another_program', 'Referred to another program'), ('dropout', 'Dropout from school')], max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('dropout_status', models.BooleanField(default=False)),
                ('moved', models.BooleanField(default=False)),
                ('outreach_barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('new_registry', models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True)),
                ('student_outreached', models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True)),
                ('have_barcode', models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, choices=[('first', 'First shift'), ('second', 'Second shift')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RSCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_cycle', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_cycle', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rs',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.RSCycle'),
        ),
        migrations.AddField(
            model_name='rs',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Disability'),
        ),
        migrations.AddField(
            model_name='rs',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='rs',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location'),
        ),
    ]
