# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-19 18:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0012_auto_20170919_2138'),
        ('clm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'enrolled'), ('pre_test', 'pre_test'), ('post_test', 'post_test')], default='enrolled', max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clm.Assessment')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth.YoungPerson')),
            ],
        ),
    ]
