# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-05 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0004_assessment_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerOrganization'),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='youth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.YoungPerson'),
        ),
    ]
