# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_pilot_in_use'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, to='locations.Location'),
        ),
    ]
