# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-09 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161124_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='partner',
        ),
    ]
