# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_beneficiary',
            field=models.BooleanField(default=False),
        ),
    ]
