# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-09 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_countryMgr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
