# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-05-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partnerorganization_dashboard_url'),
        ('users', '0008_user_is_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Center'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_center',
            field=models.BooleanField(default=False, verbose_name='Center status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_countryMgr',
            field=models.BooleanField(default=False, verbose_name='country manager status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='partner status'),
        ),
    ]
