# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-30 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partnerorganization_dashboard_url'),
        ('users', '0009_auto_20191230_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Center'),
        ),
    ]
