# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_beneficiary',
            field=models.BooleanField(default=False, verbose_name='beneficiary status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_center',
            field=models.BooleanField(default=False, verbose_name='Center status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_countryMgr',
            field=models.BooleanField(default=False, verbose_name='country manager status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='partner status'),
        ),
    ]
