# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-04-11 07:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0005_partnerorganization_dashboard_url'),
        ('locations', '0003_location_name_en'),
        ('registrations', '0022_assessmenthash_assessment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'enrolled'), ('pre_test', 'pre_test'), ('post_test', 'post_test')], default='enrolled', max_length=254)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('new_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='YouthLedent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('Participants', models.ManyToManyField(related_name='_youthledent_Participants_+', to='registrations.Registration', verbose_name='Participants')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.Center', verbose_name='Center')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Governorate')),
                ('partner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner Organization')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='entrepreneurship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepreneurship.YouthLedent'),
        ),
    ]
