# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-21 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_exporter_exported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporter',
            name='exported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Exported by'),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerOrganization', verbose_name='Partner organization'),
        ),
    ]
