# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-05-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0005_partnerorganization_dashboard_url'),
        ('locations', '0003_location_name_en'),
        ('initiatives', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthledinitiative',
            name='Participants',
            field=models.ManyToManyField(related_name='_youthledinitiative_Participants_+', to='registrations.Registration', verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='youthledinitiative',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.Center', verbose_name='Center'),
        ),
        migrations.AddField(
            model_name='youthledinitiative',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='youthledinitiative',
            name='partner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner Organization'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initiatives.YouthLedInitiative'),
        ),
    ]
