# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-07 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Initiative Title'),
        ),
    ]
