# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-14 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_name_en'),
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthledinitiative',
            name='location',
        ),
        migrations.AddField(
            model_name='youthledinitiative',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Governorate'),
        ),
    ]
