# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 08:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='age_of_beneficiaries',
            field=models.CharField(blank=True, choices=[('1-6', '1-6 \u0633\u0646\u0648\u0627\u062a'), ('7-13', '7-13 \u0633\u0646\u0648\u0627\u062a'), ('14-24', '14-24 \u0633\u0646\u0629'), ('25-50', '25-50 \u0633\u0646\u0629'), ('50-plus', '50 \u0633\u0646\u0629 \u0648\u0645\u0627 \u0641\u0648\u0642  ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='duration',
            field=models.CharField(blank=True, choices=[('1_2', '\u0623\u0633\u0628\u0648\u0639 - \u0623\u0633\u0628\u0648\u0639\u0627\u0646'), ('3_4', '3-4 \u0623\u0633\u0627\u0628\u064a\u0639'), ('4_6', '4 - 6 \u0623\u0633\u0627\u0628\u064a\u0639'), ('6_plus', '\u0623\u0643\u062b\u0631 \u0645\u0646 6 \u0623\u0633\u0627\u0628\u064a\u0639 ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='indirect_beneficiaries',
            field=models.CharField(blank=True, choices=[('1-50', '1-50'), ('51-100 ', '51-100'), ('501-1000', '501-1000'), ('1000-plus', '\u0623\u0643\u062b\u0631 \u0645\u0646 1000')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='initiative_activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('basic_services', '\u062a\u062d\u0633\u064a\u0646 \u0623\u0648 \u062a\u062b\u0628\u064a\u062a \u0627\u0644\u062e\u062f\u0645\u0627\u062a \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629 (\u0627\u0644\u0643\u0647\u0631\u0628\u0627\u0621\u060c \u0627\u0644\u0645\u064a\u0627\u0647\u060c \u0627\u0644\u0635\u0631\u0641 \u0627\u0644\u0635\u062d\u064a \u0648\u0625\u0632\u0627\u0644\u0629 \u0627\u0644\u0646\u0641\u0627\u064a\u0627\u062a)'), ('social', '\u062a\u0639\u0632\u064a\u0632 \u0627\u0644\u062a\u0645\u0627\u0633\u0643 \u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a'), ('environmental', '\u0628\u064a\u0626\u064a\u0629'), ('health_services', '\u062e\u062f\u0645\u0627\u062a \u0635\u062d\u064a\u0629'), ('informational', '\u062a\u0639\u0644\u064a\u0645\u064a\u0629\u060c \u0645\u0639\u0644\u0648\u0645\u0627\u062a\u064a\u0629 \u0623\u0648 \u062a\u0628\u0627\u062f\u0644 \u0645\u0639\u0644\u0648\u0645\u0627\u062a'), ('advocacy', '\u0627\u0644\u0645\u0646\u0627\u0635\u0631\u0629 \u0623\u0648 \u0632\u064a\u0627\u062f\u0629 \u0627\u0644\u0648\u0639\u064a'), ('political', '\u0633\u064a\u0627\u0633\u064a\u0629'), ('religious', '\u0631\u0648\u062d\u064a\u0629 / \u062f\u064a\u0646\u064a\u0629'), ('culture', '\u0641\u0646\u064a\u0629 / \u062b\u0642\u0627\u0641\u064a\u0629 / \u0631\u064a\u0627\u0636\u0629'), ('safety', '\u062a\u0639\u0632\u064a\u0632 \u0627\u0644\u0633\u0644\u0627\u0645\u0629 \u0627\u0644\u0639\u0627\u0645\u0629'), ('public_spaces', '\u062a\u062d\u0633\u064a\u0646 \u0627\u0644\u0645\u0633\u0627\u062d\u0627\u062a \u0627\u0644\u0639\u0627\u0645\u0629 (\u0627\u0644\u062d\u062f\u0627\u0626\u0642\u060c \u0627\u0644\u0645\u0633\u062a\u0634\u0641\u064a\u0627\u062a\u060c \u0627\u0644\u0645\u0628\u0627\u0646\u064a\u060c \u0627\u0644\u0645\u062f\u0627\u0631\u0633 \u0648\u0627\u0644\u0623\u0631\u0635\u0641\u0629)'), ('other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f)')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='initiative_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('basic_services', '\u062a\u062d\u0633\u064a\u0646 \u0623\u0648 \u062a\u062b\u0628\u064a\u062a \u0627\u0644\u062e\u062f\u0645\u0627\u062a \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629 (\u0627\u0644\u0643\u0647\u0631\u0628\u0627\u0621\u060c \u0627\u0644\u0645\u064a\u0627\u0647\u060c \u0627\u0644\u0635\u0631\u0641 \u0627\u0644\u0635\u062d\u064a \u0648\u0625\u0632\u0627\u0644\u0629 \u0627\u0644\u0646\u0641\u0627\u064a\u0627\u062a)'), ('social', '\u062a\u0639\u0632\u064a\u0632 \u0627\u0644\u062a\u0645\u0627\u0633\u0643 \u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a'), ('environmental', '\u0628\u064a\u0626\u064a\u0629'), ('health_services', '\u062e\u062f\u0645\u0627\u062a \u0635\u062d\u064a\u0629'), ('informational', '\u062a\u0639\u0644\u064a\u0645\u064a\u0629\u060c \u0645\u0639\u0644\u0648\u0645\u0627\u062a\u064a\u0629 \u0623\u0648 \u062a\u0628\u0627\u062f\u0644 \u0645\u0639\u0644\u0648\u0645\u0627\u062a'), ('advocacy', '\u0627\u0644\u0645\u0646\u0627\u0635\u0631\u0629 \u0623\u0648 \u0632\u064a\u0627\u062f\u0629 \u0627\u0644\u0648\u0639\u064a'), ('political', '\u0633\u064a\u0627\u0633\u064a\u0629'), ('religious', '\u0631\u0648\u062d\u064a\u0629 / \u062f\u064a\u0646\u064a\u0629'), ('culture', '\u0641\u0646\u064a\u0629 / \u062b\u0642\u0627\u0641\u064a\u0629 / \u0631\u064a\u0627\u0636\u0629'), ('safety', '\u062a\u0639\u0632\u064a\u0632 \u0627\u0644\u0633\u0644\u0627\u0645\u0629 \u0627\u0644\u0639\u0627\u0645\u0629'), ('public_spaces', '\u062a\u062d\u0633\u064a\u0646 \u0627\u0644\u0645\u0633\u0627\u062d\u0627\u062a \u0627\u0644\u0639\u0627\u0645\u0629 (\u0627\u0644\u062d\u062f\u0627\u0626\u0642\u060c \u0627\u0644\u0645\u0633\u062a\u0634\u0641\u064a\u0627\u062a\u060c \u0627\u0644\u0645\u0628\u0627\u0646\u064a\u060c \u0627\u0644\u0645\u062f\u0627\u0631\u0633 \u0648\u0627\u0644\u0623\u0631\u0635\u0641\u0629)'), ('other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f)')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='knowledge_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('self-management', '\u0627\u0644\u0625\u062f\u0627\u0631\u0629 \u0627\u0644\u0630\u0627\u062a\u064a\u0629'), ('teamwork', '\u0627\u0644\u062a\u0639\u0627\u0648\u0646 \u0648\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u062c\u0645\u0627\u0639\u064a'), ('creativity', '\u0627\u0644\u0625\u0628\u062f\u0627\u0639'), ('critical_thinking', '\u0627\u0644\u062a\u0641\u0643\u064a\u0631 \u0627\u0644\u0646\u0642\u062f\u064a'), ('negotiation', '\u0627\u0644\u062a\u0641\u0627\u0648\u0636'), ('diversity', '\u0627\u062d\u062a\u0631\u0627\u0645 \u0627\u0644\u062a\u0646\u0648\u0639'), ('decision_making', '\u0625\u062a\u062e\u0627\u0630 \u0627\u0644\u0642\u0631\u0627\u0631'), ('participation', '\u0645\u0634\u0627\u0631\u0643\u0629'), ('communication', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644\u0627\u062a'), ('empathy', '\u0627\u0644\u062a\u0639\u0627\u0637\u0641'), ('problem_solving', '\u062d\u0644 \u0627\u0644\u0645\u0634\u0627\u0643\u0644'), ('resilience', '\u0627\u0644\u0645\u0631\u0648\u0646\u0629')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='mentor_was_helpful',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627'), ('somewhat', ' \u0625\u0644\u0649 \u062d\u062f \u0645\u0627')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='number_of_beneficiaries',
            field=models.CharField(blank=True, choices=[('1-50', '1-50'), ('51-100 ', '51-100'), ('501-1000', '501-1000'), ('1000-plus', '\u0623\u0643\u062b\u0631 \u0645\u0646 1000')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='number_of_beneficiaries_reached',
            field=models.CharField(blank=True, choices=[('exceeded', '\u062a\u062c\u0627\u0648\u0632 \u0627\u0644\u0639\u062f\u062f \u0627\u0644\u0625\u062c\u0645\u0627\u0644\u064a \u0644\u0644\u0645\u0633\u062a\u0641\u064a\u062f\u064a\u0646 \u0627\u0644\u0645\u0628\u0627\u0634\u0631\u064a\u0646 \u0627\u0644\u0630\u064a\u0646 \u062e\u0637\u0637\u0646\u0627 \u0644\u0644\u0648\u0635\u0648\u0644 \u0625\u0644\u064a\u0647\u0645 (\u0623\u0643\u062b\u0631 \u0645\u0646 100\u066a)'), ('reached', '\u062a\u0645 \u0627\u0644\u0648\u0635\u0648\u0644 \u0625\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0633\u062a\u0641\u064a\u062f\u064a\u0646 \u0627\u0644\u0645\u0628\u0627\u0634\u0631\u064a\u0646 \u0627\u0644\u0645\u0642\u0631\u0651\u0631\u064a\u0646 (100\u066a)'), ('half', 'Reached more than half of the direct beneficiaries planned (50% or more)'), ('less', '\u0644\u0645 \u064a\u062a\u0645 \u0627\u0644\u0648\u0635\u0648\u0644 \u0625\u0644\u0649 \u0627\u0644\u0639\u062f\u062f \u0627\u0644\u0625\u062c\u0645\u0627\u0644\u064a \u0644\u0644\u0645\u0633\u062a\u0641\u064a\u062f\u064a\u0646 \u0627\u0644\u0645\u0628\u0627\u0634\u0631\u064a\u0646 (\u0623\u0642\u0644 \u0645\u0646 49\u066a)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='other_groups',
            field=models.CharField(blank=True, choices=[('ngos', '\u0645\u0646\u0638\u0645\u0627\u062a \u063a\u064a\u0631 \u062d\u0643\u0648\u0645\u064a\u0629 \u0623\u062e\u0631\u0649'), ('schools', '\u0627\u0644\u0645\u062f\u0627\u0631\u0633'), ('municipality', '\u0627\u0644\u0628\u0644\u062f\u064a\u0629 '), ('other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='resources_from',
            field=models.CharField(blank=True, choices=[('unicef', '\u0627\u0644\u064a\u0648\u0646\u064a\u0633\u064a\u0641'), ('local ', '\u0634\u0631\u0643\u0629 \u0645\u062d\u0644\u064a\u0629'), ('organization', '\u0645\u0646\u0638\u0645\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='resources_type',
            field=models.CharField(blank=True, choices=[('financial', '\u0645\u0627\u0644\u064a (\u0630\u0627\u062a\u064a \u0627\u0644\u062a\u0641\u0633\u064a\u0631)'), ('technical', '\u062a\u0642\u0646\u064a (\u0639\u0644\u0649 \u0633\u0628\u064a\u0644 \u0627\u0644\u0645\u062b\u0627\u0644 \u062a\u0637\u0648\u064a\u0631 \u0645\u0648\u0627\u062f \u0623\u062f\u0648\u0627\u062a \u0627\u0644\u062a\u0648\u0639\u064a\u0629\u060c \u0627\u0644\u062a\u062f\u0631\u064a\u0628 ... \u0627\u0644\u062e)'), ('in-kind', '\u0639\u064a\u0646\u064a (\u0645\u0644\u0635\u0642\u0627\u062a\u060c \u0643\u062a\u064a\u0628\u0627\u062a ... \u0627\u0644\u062e)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='sex_of_beneficiaries',
            field=models.CharField(blank=True, choices=[('both', '\u0627\u0644\u0630\u0643\u0648\u0631 \u0648\u0627\u0644\u0625\u0646\u0627\u062b \u0639\u0644\u0649 \u062d\u062f \u0633\u0648\u0627\u0621'), ('male', '\u0627\u0644\u0630\u0643\u0648\u0631 \u0641\u0642\u0637 '), ('female', '\u0627\u0644\u0625\u0646\u0627\u062b \u0641\u0642\u0637 ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='support_helpful',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627'), ('somewhat', ' \u0625\u0644\u0649 \u062d\u062f \u0645\u0627')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='team_participation_rating',
            field=models.CharField(blank=True, choices=[('excellent', '\u0645\u0645\u062a\u0627\u0632\u0629 - \u062c\u0645\u064a\u0639 \u0623\u0639\u0636\u0627\u0621 \u0641\u0631\u064a\u0642\u0646\u0627 \u0625\u0644\u062a\u0632\u0645\u0648\u0627 \u0628\u0627\u0644\u0645\u0628\u0627\u062f\u0631\u0629'), ('good', '\u062c\u064a\u062f\u0629 - \u0643\u0627\u0646 \u0645\u0639\u0638\u0645 \u0641\u0631\u064a\u0642\u0646\u0627 \u0645\u0644\u062a\u0632\u0645\u0627\u064b \u0628\u0647\u0630\u0647 \u0627\u0644\u0645\u0628\u0627\u062f\u0631\u0629'), ('low', '\u0645\u0646\u062e\u0641\u0636\u0629 - \u062a\u0648\u0642\u0651\u0641 \u0628\u0639\u0636 \u0623\u0639\u0636\u0627\u0621 \u0627\u0644\u0641\u0631\u064a\u0642 \u0639\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629')], max_length=100, null=True),
        ),
    ]
