# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-16 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthledinitiative',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='duration',
            field=models.CharField(blank=True, choices=[('1_2', '1-2 weeks'), ('3_4', '3-4 weeks'), ('4_6', '4-6 weeks'), ('6_plus', 'More than 6 weeks')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='initiative_types',
            field=models.CharField(blank=True, choices=[('basic_services', 'Improving or installing basic services (electricity, water, sanitation, and waste removal)'), ('social', 'Enhancing social cohesion'), ('environmental', 'Environmental'), ('health_services', 'Health Services'), ('informational', 'Educational, informational or knowledge sharing'), ('advocacy', 'Advocacy or Raising awareness'), ('political', 'Political'), ('religious', 'Spiritual/Religious'), ('culture', 'Artistic/Cultural/Sports'), ('safety', 'Enhancing public safety'), ('public_spaces', 'Improving Public Spaces (parks, hospitals, buildings, schools, sidewalks)'), ('other', 'Other')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='members',
            field=models.ManyToManyField(blank=True, to='youth.YoungPerson'),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='partner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='partner_organization'),
        ),
    ]
