# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-17 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_auto_20181216_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='members',
            field=models.ManyToManyField(blank=True, to='registrations.Registration'),
        ),
    ]
