# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-28 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partnerorganization_dashboard_url'),
        ('initiatives', '0002_auto_20190507_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthledinitiative',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.Center', verbose_name='Center'),
        ),
    ]
