# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-19 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_auto_20180917_1333'),
        ('initiatives', '0002_auto_20181216_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthledinitiative',
            name='member',
            field=models.ManyToManyField(blank=True, to='registrations.Registration'),
        ),
    ]
