# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_auto_20170426_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='members',
            field=models.ManyToManyField(blank=True, to='youth.YoungPerson'),
        ),
    ]
