# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-21 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_youthledinitiative_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthledinitiative',
            name='members',
        ),
    ]
