# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-30 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_youthledinitiative_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthledinitiative',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Governorate'),
        ),
    ]
