# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-17 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_auto_20181217_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthledinitiative',
            name='members',
        ),
    ]
