# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-24 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import referral_platform.registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_remove_youthledinitiative_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='member',
            field=models.ManyToManyField(blank=True, related_query_name=referral_platform.registrations.models.AssessmentSubmission, to='registrations.Registration'),
        ),
    ]
