# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-16 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_auto_20191216_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
