# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-24 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_auto_20181224_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='member',
            field=models.ManyToManyField(blank=True, to='registrations.Registration'),
        ),
    ]
