# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-17 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0021_nationality_name_en'),
        ('initiatives', '0005_remove_youthledinitiative_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthledinitiative',
            name='member',
            field=models.ManyToManyField(blank=True, to='youth.YoungPerson'),
        ),
    ]
