# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-05 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_auto_20171212_1804'),
        ('initiatives', '0006_auto_20171221_1453'),
    ]

    operations = [
    ]
