# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-03 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0008_auto_20190102_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthledinitiative',
            name='description',
        ),
    ]
