# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0009_auto_20180917_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthledinitiative',
            name='initiative_types',
        ),
        migrations.RemoveField(
            model_name='youthledinitiative',
            name='knowledge_areas',
        ),
    ]
