# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-14 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0011_auto_20181214_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youthledinitiative',
            name='initiative_types',
        ),
    ]
