# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-22 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0015_auto_20190122_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentHash',
        ),
    ]
