# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-19 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0016_delete_assessmenthash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='Participants',
            field=models.ManyToManyField(related_name='_youthledinitiative_Participants_+', to='registrations.Registration', verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='duration',
            field=models.CharField(blank=True, choices=[('1_2', '1-2 weeks'), ('3_4', '3-4 weeks'), ('4_6', '4-6 weeks'), ('6_plus', 'More than 6 weeks')], max_length=254, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='partner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner_Organization'),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
