# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-01 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0019_auto_20190401_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='duration',
            field=models.CharField(blank=True, choices=[('1_2', '1-2 weeks'), ('3_4', '3-4 weeks'), ('4_6', '4-6 weeks'), ('6_plus', 'More than 6 weeks')], max_length=254, null=True, verbose_name='Duration of the initiative'),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Initiative Location'),
        ),
        migrations.AlterField(
            model_name='youthledinitiative',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Initiative Title'),
        ),
    ]
