# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-01 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0020_auto_20190401_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='type',
            field=models.CharField(blank=True, choices=[('basic services', 'Basic Services'), ('social Cohesion', 'Social cohesion'), ('environmental', 'Environmental'), ('health services', 'Health Services'), ('protection', 'Protection'), ('advocacy', 'Advocacy or Raising awareness'), ('political', 'Political'), ('religious and spiritual', 'Spiritual/Religious'), ('sports', 'Sports'), ('economic art cultural', 'Economic art cultural'), ('educational', 'educational'), ('other', 'Other')], max_length=254, null=True, verbose_name='Initiative Types'),
        ),
    ]
