# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-01 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0021_auto_20190401_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='Participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='_youthledinitiative_Participants_+', to='registrations.Registration', verbose_name='Participants'),
        ),
    ]
