# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0022_auto_20190401_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youthledinitiative',
            name='type',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Initiative Types'),
        ),
    ]
