# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['id'], 'verbose_name': '\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a'},
        ),
        migrations.AlterModelOptions(
            name='idtype',
            options={'ordering': ['id'], 'verbose_name': '\u0646\u0648\u0639 \u0627\u0644\u0647\u0648\u064a\u0629'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['id'], 'verbose_name_plural': '\u0627\u0644\u062c\u0646\u0633\u064a\u0627\u062a'},
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='birthday_month',
            field=models.CharField(blank=True, choices=[('1', '\u0643\u0627\u0646\u0648\u0646 \u0627\u0644\u062b\u0627\u0646\u064a'), ('2', '\u0634\u0628\u0627\u0637'), ('3', '\u0622\u0630\u0627\u0631'), ('4', '\u0646\u064a\u0633\u0627\u0646'), ('5', '\u0627\u064a\u0627\u0631'), ('6', '\u062d\u0632\u064a\u0631\u0627\u0646'), ('7', '\u062a\u0645\u0648\u0632'), ('8', '\u0622\u0628'), ('9', '\u0627\u064a\u0644\u0648\u0644'), ('10', '\u062a\u0634\u0631\u064a\u0646 \u0627\u0648\u0644'), ('11', '\u062a\u0634\u0631\u064a\u0646 \u062b\u0627\u0646\u064a'), ('12', '\u0643\u0627\u0646\u0648\u0646 \u0627\u0648\u0644')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='communication_preference',
            field=models.CharField(blank=True, choices=[('facebook', '\u0641\u0627\u064a\u0633\u0628\u0648\u0643\u060c \u0648\u0625\u0630\u0627 \u0643\u0627\u0646 \u0627\u0644\u0623\u0645\u0631 \u0643\u0630\u0644\u0643\u060c \u064a\u0631\u062c\u0649 \u062a\u062f\u0648\u064a\u0646 \u0627\u0633\u0645 \u062d\u0633\u0627\u0628\u0643'), ('email', '\u0627\u0644\u0628\u0631\u064a\u062f \u0627\u0644\u0625\u0644\u0643\u062a\u0631\u0648\u0646\u064a\u060c \u0648\u0625\u0630\u0627 \u0643\u0627\u0646 \u0627\u0644\u0623\u0645\u0631 \u0643\u0630\u0644\u0643\u060c \u064a\u0631\u062c\u0649 \u062a\u062f\u0648\u064a\u0646\u0647'), ('mobile', '\u0627\u0644\u0647\u0627\u062a\u0641 \u0627\u0644\u0645\u062d\u0645\u0648\u0644'), ('ngo', '\u0645\u0646 \u062e\u0644\u0627\u0644 \u0634\u0631\u064a\u0643 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u063a\u064a\u0631 \u0627\u0644\u062d\u0643\u0648\u0645\u064a\u0629'), ('none', '\u0623\u0646\u0627 \u0644\u0627 \u0623\u0631\u064a\u062f \u0627\u0644\u0645\u062a\u0627\u0628\u0639\u0629 ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='education_status',
            field=models.CharField(choices=[('currently_studying', '\u0646\u0639\u0645\u060c \u0623\u0646\u0627 \u0623\u062f\u0631\u0633 \u062d\u0627\u0644\u064a\u0627\u064b'), ('stopped_studying', '\u0646\u0639\u0645\u060c \u0648\u0644\u0643\u0646 \u062a\u0648\u0642\u0651\u0641\u062a \u0639\u0646 \u0627\u0644\u062f\u0631\u0627\u0633\u0629'), ('never_studied', '\u0644\u0627\u060c \u0644\u0645 \u0623\u0630\u0647\u0628 \u0623\u0628\u062f\u0627\u064b \u0625\u0644\u0649 \u0623\u064a \u0645\u0624\u0633\u0633\u0629 \u0623\u0643\u0627\u062f\u064a\u0645\u064a\u0629'), ('na', '\u063a\u064a\u0631 \u0645\u062d\u062f\u062f')], max_length=50),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='education_type',
            field=models.CharField(choices=[('non-formal', "'\u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a"), ('formal', '\u062a\u0639\u0644\u064a\u0645 \u0646\u0638\u0627\u0645\u064a')], max_length=50),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='employment_status',
            field=models.CharField(choices=[('full_time', '\u0623\u0639\u0645\u0644 \u062d\u0627\u0644\u064a\u0627\u064b - \u0628\u062f\u0648\u0627\u0645 \u0643\u0627\u0645\u0644'), ('part_time', '\u0623\u0639\u0645\u0644 \u062d\u0627\u0644\u064a\u0627\u064b - \u0628\u062f\u0648\u0627\u0645 \u062c\u0632\u0626\u064a'), ('summer_only', '\u0623\u0639\u0645\u0644 \u0641\u064a \u0641\u0635\u0644 \u0627\u0644\u0635\u064a\u0641 \u0641\u0642\u0637'), ('unemployed', '\u062d\u0627\u0644\u064a\u0627\u064b \u0639\u0627\u0637\u0644 \u0639\u0646 \u0627\u0644\u0639\u0645\u0644'), ('never_worked', '\u0644\u0645 \u062a\u0639\u0645\u0644')], max_length=50),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='not_trained_reason',
            field=models.CharField(blank=True, choices=[('no_interest', '\u0642\u0644\u0629 \u0627\u0647\u062a\u0645\u0627\u0645'), ('no_money', '\u0639\u0627\u0626\u0642 \u0645\u0627\u0644\u064a'), ('family_pressure', '\u0636\u063a\u0637 \u0627\u0644\u0623\u0633\u0631\u0629'), ('discrimination', '\u0627\u0644\u062a\u0645\u064a\u064a\u0632'), ('disability', '\u0625\u0639\u0627\u0642\u0629'), ('distance', ' \u0627\u0644\u0645\u0633\u0627\u0641\u0629'), ('safety', '\u0627\u0644\u0633\u0644\u0627\u0645\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='referred_by',
            field=models.CharField(blank=True, choices=[('ngo', '\u0645\u0646 \u062e\u0644\u0627\u0644 \u0645\u0646\u0638\u0645\u0629 \u063a\u064a\u0631 \u062d\u0643\u0648\u0645\u064a\u0629 \u0623\u062e\u0631\u0649'), ('sports_ngo', '\u0645\u0646 \u062e\u0644\u0627\u0644 \u0646\u0627\u062f\u064d \u0631\u064a\u0627\u0636\u064a / \u0645\u0646\u0638\u0645\u0629 \u063a\u064a\u0631 \u062d\u0643\u0648\u0645\u064a\u0629'), ('friends', '\u0645\u0646 \u062e\u0644\u0627\u0644 \u0627\u0644\u0623\u0635\u062f\u0642\u0627\u0621'), ('others', '\u0648\u0633\u0627\u0626\u0644 \u0623\u062e\u0631\u0649')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='safety',
            field=models.CharField(blank=True, choices=[('safe', '\u0623\u0634\u0639\u0631 \u062f\u0627\u0626\u0645\u0627\u064b \u0628\u0623\u0645\u0627\u0646 \u062a\u0627\u0645 \u0641\u064a \u0645\u062c\u062a\u0645\u0639\u064a'), ('mostly_safe', '\u0623\u0634\u0639\u0631 \u0641\u064a \u0645\u0639\u0638\u0645 \u0627\u0644\u0623\u064a\u0627\u0645 \u0628\u0623\u0645\u0627\u0646 \u0641\u064a \u0645\u062c\u062a\u0645\u0639\u064a'), ('mostly_unsafe', '\u0644\u0627 \u0623\u0634\u0639\u0631 \u0641\u064a \u0645\u0639\u0638\u0645 \u0627\u0644\u0623\u064a\u0627\u0645 \u0628\u0623\u0645\u0627\u0646 \u0641\u064a \u0645\u062c\u062a\u0645\u0639\u064a'), ('unsafe', '\u0644\u0645 \u0623\u0634\u0639\u0631 \u0628\u0627\u0644\u0623\u0645\u0627\u0646 \u0641\u064a \u0645\u062c\u062a\u0645\u0639\u064a \u064a\u0648\u0645\u0627\u064b ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='sex',
            field=models.CharField(choices=[('Male', '\u0630\u0643\u0631'), ('Female', '\u0627\u0646\u062b\u0649')], max_length=50),
        ),
    ]
