# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-30 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0002_auto_20170426_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['id'], 'verbose_name': '\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a', 'verbose_name_plural': '\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a'},
        ),
        migrations.AlterModelOptions(
            name='idtype',
            options={'ordering': ['id'], 'verbose_name': '\u0646\u0648\u0639 \u0627\u0644\u0647\u0648\u064a\u0629', 'verbose_name_plural': '\u0646\u0648\u0639 \u0627\u0644\u0647\u0648\u064a\u0629'},
        ),
        migrations.AlterModelOptions(
            name='youngperson',
            options={'ordering': ['first_name'], 'verbose_name': 'Youth', 'verbose_name_plural': 'Youth'},
        ),
    ]
