# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-04 14:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0003_auto_20170530_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youngperson',
            name='employment_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='household_composition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='leaving_education_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='not_trained_reason',
            field=models.CharField(blank=True, choices=[('no_interest', '\u0642\u0644\u0629 \u0627\u0647\u062a\u0645\u0627\u0645'), ('no_money', '\u0639\u0627\u0626\u0642 \u0645\u0627\u0644\u064a'), ('family_pressure', '\u0636\u063a\u0637 \u0627\u0644\u0623\u0633\u0631\u0629'), ('discrimination', '\u0627\u0644\u062a\u0645\u064a\u064a\u0632'), ('disability', '\u0644\u062f\u064a\u0643 \u0627\u064a \u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629\u061f'), ('distance', ' \u0627\u0644\u0645\u0633\u0627\u0641\u0629'), ('safety', '\u0627\u0644\u0633\u0644\u0627\u0645\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='obstacles_for_work',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='safety_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
    ]
