# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0004_auto_20170704_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youngperson',
            name='id_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youth.IDType'),
        ),
    ]
