# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-15 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0005_auto_20170713_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youngperson',
            name='education_type',
            field=models.CharField(blank=True, choices=[('non-formal', '\u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a'), ('formal', '\u062a\u0639\u0644\u064a\u0645 \u0646\u0638\u0627\u0645\u064a')], max_length=50, null=True),
        ),
    ]
