# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-15 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0006_auto_20170715_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youngperson',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youth.EducationLevel'),
        ),
    ]
