# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-17 11:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0008_auto_20170717_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youngperson',
            name='employment_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='employment_status',
            field=models.CharField(choices=[('full_time', '\u0623\u0639\u0645\u0644 \u062d\u0627\u0644\u064a\u0627\u064b - \u0628\u062f\u0648\u0627\u0645 \u0643\u0627\u0645\u0644'), ('part_time', '\u0623\u0639\u0645\u0644 \u062d\u0627\u0644\u064a\u0627\u064b - \u0628\u062f\u0648\u0627\u0645 \u062c\u0632\u0626\u064a'), ('summer_only', '\u0623\u0639\u0645\u0644 \u0641\u064a \u0641\u0635\u0644 \u0627\u0644\u0635\u064a\u0641 \u0641\u0642\u0637'), ('unemployed', '\u062d\u0627\u0644\u064a\u0627\u064b \u0639\u0627\u0637\u0644 \u0639\u0646 \u0627\u0644\u0639\u0645\u0644'), ('never_worked', '\u0644\u0645 \u062a\u0639\u0645\u0644'), ('looking_for_work', '\u0627\u0628\u062d\u062b \u0639\u0646 \u0639\u0645\u0644')], max_length=50),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='obstacles_for_work',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
    ]
