# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0009_auto_20170717_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='youngperson',
            name='communication_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
