# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0010_youngperson_communication_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='youngperson',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('engaged', 'Engaged'), ('divorced', 'Divorced'), ('widower', 'Widower'), ('single', 'Single')], max_length=50, null=True),
        ),
    ]
