# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-19 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0011_auto_20170919_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youngperson',
            name='education_status',
            field=models.CharField(blank=True, choices=[('currently_studying', '\u0646\u0639\u0645\u060c \u0623\u0646\u0627 \u0623\u062f\u0631\u0633 \u062d\u0627\u0644\u064a\u0627\u064b'), ('stopped_studying', '\u0646\u0639\u0645\u060c \u0648\u0644\u0643\u0646 \u062a\u0648\u0642\u0651\u0641\u062a \u0639\u0646 \u0627\u0644\u062f\u0631\u0627\u0633\u0629'), ('never_studied', '\u0644\u0627\u060c \u0644\u0645 \u0623\u0630\u0647\u0628 \u0623\u0628\u062f\u0627\u064b \u0625\u0644\u0649 \u0623\u064a \u0645\u0624\u0633\u0633\u0629 \u0623\u0643\u0627\u062f\u064a\u0645\u064a\u0629'), ('na', '\u063a\u064a\u0631 \u0645\u062d\u062f\u062f')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='mother_firstname',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='mother_fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='mother_lastname',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='partner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization'),
        ),
    ]
