# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-21 13:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_center'),
        ('locations', '0002_remove_location_pilot_in_use'),
        ('youth', '0014_remove_youngperson_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['id'], 'verbose_name': 'ALP Level', 'verbose_name_plural': 'ALP Level'},
        ),
        migrations.AlterModelOptions(
            name='idtype',
            options={'ordering': ['id'], 'verbose_name': 'ID Type', 'verbose_name_plural': 'ID Type'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['id'], 'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AddField(
            model_name='youngperson',
            name='bayanati_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bayanati ID'),
        ),
        migrations.AddField(
            model_name='youngperson',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Center'),
        ),
        migrations.AddField(
            model_name='youngperson',
            name='governorate',
            field=models.ForeignKey(default='39', on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='youngperson',
            name='trainer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='code',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='age',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='birthday_day',
            field=models.CharField(choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, verbose_name='birthday day'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='birthday_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, verbose_name='birthday month'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='birthday_year',
            field=models.CharField(choices=[(b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004), (b'2005', 2005), (b'2006', 2006), (b'2007', 2007), (b'2008', 2008), (b'2009', 2009), (b'2010', 2010)], default=1991, max_length=4, verbose_name='birthday year'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='communication_preference',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('email', 'E-mail'), ('mobile', 'Mobile'), ('ngo', 'Through the NGO partner'), ('none', "I don't want follow up")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='education_status',
            field=models.CharField(blank=True, choices=[('currently_studying', 'Yes, I am currently studying'), ('stopped_studying', 'Yes, but I stopped studying'), ('never_studied', 'Never been to an educational institution'), ('na', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='education_type',
            field=models.CharField(blank=True, choices=[('non-formal', 'Non formal Education'), ('formal', 'Formal Education')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('full_time', 'Currently Working - full time'), ('part_time', 'Currently Working - part time'), ('summer_only', 'Work in Summer Only'), ('unemployed', 'Currently Unemployed'), ('never_worked', 'Never worked'), ('looking_for_work', 'Looking for a work')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='father_name',
            field=models.CharField(max_length=75, validators=[django.core.validators.RegexValidator('^[\u0600-\u065f\u066e-\u06ff ]*$', 'Only Arabic characters are allowed.')], verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='first_name',
            field=models.CharField(max_length=75, validators=[django.core.validators.RegexValidator('^[\u0600-\u065f\u066e-\u06ff ]*$', 'Only Arabic characters are allowed.')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='full_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='last_name',
            field=models.CharField(max_length=75, validators=[django.core.validators.RegexValidator('^[\u0600-\u065f\u066e-\u06ff ]*$', 'Only Arabic characters are allowed.')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='marital_status',
            field=models.CharField(choices=[('', 'Marital status'), ('married', 'Married'), ('engaged', 'Engaged'), ('divorced', 'Divorced'), ('widower', 'Widower'), ('single', 'Single')], default='single', max_length=50, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='not_trained_reason',
            field=models.CharField(blank=True, choices=[('no_interest', 'No Interest'), ('no_money', 'Financial barrier'), ('family_pressure', 'Family pressure'), ('discrimination', 'Discrimination'), ('disability', 'Disability'), ('distance', 'Distance'), ('safety', 'Safety')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='referred_by',
            field=models.CharField(blank=True, choices=[('ngo', 'Through an NGO'), ('sports_ngo', 'Through a Sports Club/NGO'), ('friends', 'Through friends'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='safety',
            field=models.CharField(blank=True, choices=[('safe', ' I always feel totally safe in my community '), ('mostly_safe', 'Most of the days I feel safe in my community'), ('mostly_unsafe', "Most of the days I don't feel safe in my community "), ('unsafe', 'I never feel safe in my community')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='sex',
            field=models.CharField(choices=[('', 'Gender'), ('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='Gender'),
        ),
    ]
