# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-22 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_pilot_in_use'),
        ('partners', '0004_center'),
        ('youth', '0015_auto_20171221_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='youngperson',
            name='bayanati_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bayanati ID'),
        ),
        migrations.AddField(
            model_name='youngperson',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Center'),
        ),
        migrations.AddField(
            model_name='youngperson',
            name='governorate',
            field=models.ForeignKey(default='39', on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='youngperson',
            name='trainer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
    ]
