# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-24 14:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_center'),
        ('locations', '0002_remove_location_pilot_in_use'),
        ('youth', '0015_auto_20171216_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='youngperson',
            name='bayanati_ID',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Bayanati ID should be composed of exactly 6 numbers .')], verbose_name='Bayanati ID'),
        ),
        migrations.AddField(
            model_name='youngperson',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Center'),
        ),
        migrations.AddField(
            model_name='youngperson',
            name='governorate',
            field=models.ForeignKey(default='39', on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='youngperson',
            name='trainer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='code',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
    ]
