# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-05 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0016_auto_20171222_1014'),
        ('youth', '0015_auto_20171216_1429'),
    ]

    operations = [
    ]
