# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-05 09:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0017_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youngperson',
            name='bayanati_ID',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Bayanati ID should be composed of exactly 6 numbers .')], verbose_name='Bayanati ID'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='birthday_year',
            field=models.CharField(choices=[(b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004), (b'2005', 2005), (b'2006', 2006), (b'2007', 2007), (b'2008', 2008), (b'2009', 2009), (b'2010', 2010), (b'2011', 2011)], default=1992, max_length=4, verbose_name='Birthday year'),
        ),
    ]
