# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-05 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0018_auto_20180105_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youngperson',
            name='bayanati_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bayanati ID'),
        ),
        migrations.AlterField(
            model_name='youngperson',
            name='birthday_year',
            field=models.CharField(choices=[(b'1968', 1968), (b'1969', 1969), (b'1970', 1970), (b'1971', 1971), (b'1972', 1972), (b'1973', 1973), (b'1974', 1974), (b'1975', 1975), (b'1976', 1976), (b'1977', 1977), (b'1978', 1978), (b'1979', 1979), (b'1980', 1980), (b'1981', 1981), (b'1982', 1982), (b'1983', 1983), (b'1984', 1984), (b'1985', 1985), (b'1986', 1986), (b'1987', 1987), (b'1988', 1988), (b'1989', 1989), (b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004), (b'2005', 2005), (b'2006', 2006), (b'2007', 2007), (b'2008', 2008), (b'2009', 2009), (b'2010', 2010), (b'2011', 2011), (b'2012', 2012), (b'2013', 2013)], default=1992, max_length=4, verbose_name='Birthday year'),
        ),
    ]
