# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0020_auto_20180626_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='Nationality En'),
        ),
    ]
