# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-01 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_pilot_in_use'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='email',
            field=models.EmailField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='locations',
            field=models.ManyToManyField(blank=True, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
