# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-10 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20170601_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='partner',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
