# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-01 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='dashboard_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
