# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-05-04 15:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0005_partnerorganization_dashboard_url'),
        ('locations', '0003_location_name_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youth', '0023_auto_20200310_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('assessment_form', models.URLField(blank=True, null=True)),
                ('order', models.TextField(default=1)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed', models.CharField(max_length=254, unique=True)),
                ('registration', models.CharField(max_length=20)),
                ('assessment_slug', models.CharField(max_length=50)),
                ('assessment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('partner', models.CharField(max_length=5)),
                ('user', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'enrolled'), ('pre_test', 'pre_test'), ('post_test', 'post_test')], default='enrolled', max_length=254)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('new_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('updated', models.CharField(default='0', max_length=254)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='NewMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=254, null=True, verbose_name='Assessment Type')),
                ('key', models.CharField(blank=True, max_length=254, null=True, verbose_name='Key')),
                ('old_value', models.CharField(blank=True, max_length=254, null=True, verbose_name='Old Value')),
                ('new_value', models.CharField(blank=True, max_length=254, null=True, verbose_name='New Value')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('location', models.CharField(blank=True, max_length=254, null=True, verbose_name='Location')),
                ('trainer', models.CharField(blank=True, max_length=254, null=True, verbose_name='Trainer')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.Center', verbose_name='Center')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Governorate')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('partner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerOrganization', verbose_name='Partner organization')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='youth.YoungPerson', verbose_name='Youth')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.Registration'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='youth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youth.YoungPerson'),
        ),
    ]
