# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-12 16:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0004_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youth', '0014_remove_youngperson_user'),
        ('locations', '0002_remove_location_pilot_in_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('assessment_form', models.URLField(blank=True, null=True)),
                ('order', models.TextField(default=1)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'enrolled'), ('pre_test', 'pre_test'), ('post_test', 'post_test')], default='enrolled', max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Assessment')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth.YoungPerson')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0645\u0648\u0642\u0639 \u0627\u0644\u062c\u063a\u0631\u0627\u0641\u064a')),
                ('trainer', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0645\u062f\u0631\u0628')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.Center', verbose_name='Center')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('partner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerOrganization', verbose_name='Partner organization')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='youth.YoungPerson', verbose_name='Youth')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name': '\u0627\u0644\u062a\u0633\u062c\u064a\u0644',
                'verbose_name_plural': 'Registrations',
            },
        ),
    ]
