# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-05-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Country'),
        ),
    ]
