# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='registration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registrations.Registration'),
            preserve_default=False,
        ),
    ]
