# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-05 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20180105_1121'),
        ('registrations', '0003_auto_20171224_1623'),
    ]

    operations = [
    ]
