# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-25 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=20)),
                ('assessment_slug', models.CharField(max_length=15)),
                ('partner', models.CharField(max_length=5)),
                ('user', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
