# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-26 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_assessmenthash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenthash',
            name='hashed',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
