# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20180226_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenthash',
            name='assessment_slug',
            field=models.CharField(max_length=50),
        ),
    ]
