# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-23 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20180226_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
