# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-23 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_registration_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='\u0645\u0644\u0627\u062d\u0638\u0627\u062a'),
        ),
    ]
