# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-21 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20180323_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['pk'], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='partner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerOrganization', verbose_name='Partner organization'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='trainer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trainer'),
        ),
    ]
