# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 11:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_remove_registration_training_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Assessment Type')),
                ('key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Key')),
                ('old_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Old Value')),
                ('new_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='New Value')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='new_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
