# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_auto_20180906_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenthash',
            name='hashed',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='status',
            field=models.CharField(choices=[('enrolled', 'enrolled'), ('pre_test', 'pre_test'), ('post_test', 'post_test')], default='enrolled', max_length=254),
        ),
        migrations.AlterField(
            model_name='newmapping',
            name='key',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='newmapping',
            name='new_value',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='New Value'),
        ),
        migrations.AlterField(
            model_name='newmapping',
            name='old_value',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Old Value'),
        ),
        migrations.AlterField(
            model_name='newmapping',
            name='type',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Assessment Type'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='trainer',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Trainer'),
        ),
    ]
