# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-02 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_auto_20180917_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='youth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youth.YoungPerson'),
        ),
    ]
