# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_auto_20190102_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.Registration'),
        ),
    ]
