# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-22 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_auto_20190102_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitAssessmentHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed', models.CharField(max_length=254, unique=True)),
                ('registration', models.CharField(max_length=20)),
                ('assessment_slug', models.CharField(max_length=50)),
                ('partner', models.CharField(max_length=5)),
                ('user', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
            ],
        ),
    ]
