# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-19 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_initassessmenthash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InitAssessmentHash',
        ),
    ]
