# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0020_assessmentsubmission_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenthash',
            name='assessment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
