# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-05-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_name_en'),
        ('registrations', '0021_assessmenthash_assessment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='assessmenthash',
            name='assessment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='slug',
            field=models.SlugField(),
        ),
    ]
