# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-31 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_auto_20191219_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenthash',
            name='assessment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
